### PR TITLE
bugfix/hack for importer.py to work with 0.5.3 exports

### PR DESCRIPTION
**Pull request by gadeleon**
Had trouble importing a 0.5.3 export (was getting an IndexError: Out of range). Made this hack to deal with that error... sorta. (Not wrapped in a try/catch but probably should be).

### CODE REVIEW

**Comment by oz123** [comment]
@gadeleon, 

I appreciate the PR, but you are hard coding the delimeter to '|', which fixes a hard coding I did to ';'. 
The correct way to solve this would be to fix the code to detect the correct delimeter. 
The place for this fix would be in ` def _read_file(self):` in the Importer class.

**Comment by gadeleon** [comment]
Noted! Looks like the help text for 0.7's export still says | is the
delimiter when it changed to semicolon; did you phase out pipes completely?
Trying to think of a modular way to address the issue in case you want to
change the delimiter again in the future.

**Comment by oz123** [comment]
@gadeleon , 
I didn't phase out any delitmeter, you can specify either pipe or `;` or what ever seperator you want. 
For some reasone I thought it was a good idea. Now, we have those versions out in the wild so that the importer needs to know the delimeter or detect it. 
I think specifying it as an

**Comment by gadeleon** [comment]
tweaked the branch such that --import now needs a file delimiter.

**Comment by oz123** [comment]
@gadeleon , 

OK, this looks much better, but the tests fail...

I realize setting a complete development environment is not easy, but I would not like to merge a PR where tests don't pass.

**Pull request closed without merging**
