### PR TITLE
MariaDB test

### PR DESCRIPTION
**Pull request by grooverdan**
Closes: #93

There's currently a problem in that the MariaDB tables aren't created.

Do you see why? I assume I've got some inheritance incorrect.

Also integration test failures still show as passed on github actions (but this was the case previously too).

### CODE REVIEW

**Comment by oz123** [comment]
Hi Dan! Thank you for your contribution. 
It seems that one table is not being properly created in mariadb:

 ```
 pymysql.err.ProgrammingError: (1146, "Table 'pwmantest.CRYPTO' doesn't exist")
```

Can you try and figure out why?

**Comment by oz123** [comment]
The error still persists ... unfortunately.

**Comment by grooverdan** [comment]
Yep, but now at least I can see the create tables failing rather than never being called.
```
 test_1_con (tests.test_mysql.TestMariaDBDatabase) ... ok
test_2_create_tables (tests.test_mysql.TestMariaDBDatabase) ... FAIL

======================================================================
FAIL: test_2_create_tables (tests.test_mysql.TestMariaDBDatabase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/pwman3/pwman3/tests/test_mysql.py", line 68, in test_2_create_tables
    self.assertTrue(self.db._check_tables())
AssertionError: 0 is not true

----------------------------------------------------------------------
```

**Comment by oz123** [comment]
I did some more digging, it turns out that mariadb does not tolerate my poor SQL skills, while mysql does.

When debugging creation of the tables in mariadb:

```
-> self._cur.execute("CREATE TABLE LOOKUP ("
(Pdb) n
pymysql.err.OperationalError: (1005, 'Can\'t create table `pwmantest`.`LOOKUP` (errno: 150 "Foreign key constraint is incorrectly formed")')
> /srv/oznt/Software/pwman3/pwman/data/database.py(76)_create_tables()
-> self._cur.execute("CREATE TABLE LOOKUP ("
```

This does not rais an exception in mysql.

**Comment by grooverdan** [comment]
Noted. Can reproduce. SERIAL corresponds to a BIGINT in MariaDB so its not matching. I'll see if I can come up with a compatible syntax. The MySQL version in the CI, 5.7 is now EOL too. So we might be just a bad.

**Comment by oz123** [comment]
@grooverdan Thank you for your contribution. I merge your commits in #96.

**Pull request closed without merging**
